# Site settings
title: Code thoughts by bwestlin
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts and ideas about coding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bwestlin.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  bwestlin

# Build settings
#markdown: kramdown
markdown: redcarpet

redcarpet:
  extensions: []

kramdown:
  input: GFM
  use_coderay: true
